import streamlit as st
import google.generativeai as genai
import json
import os
from fpdf import FPDF

# --- PAGE CONFIG ---
st.set_page_config(page_title="Advanced Patent Suite", page_icon="🛡️", layout="wide")

# --- CUSTOM CSS ---
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #007bff; color: white; font-weight: bold; }
    .report-box { padding: 20px; border-radius: 10px; background-color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 20px; }
    .novelty-score { font-size: 48px; font-weight: bold; text-align: center; color: #007bff; }
    .patent-card { padding: 15px; border-left: 5px solid #28a745; background-color: #f8f9fa; margin-bottom: 10px; border-radius: 0 5px 5px 0; }
    </style>
    """, unsafe_allow_html=True)

# --- SIDEBAR ---
with st.sidebar:
    st.title("🛡️ Suite Config")
    
    # Priority 1: Check for Shared/Master Key
    shared_key = ""
    try:
        shared_key = st.secrets.get("gemini_key") or \
                     os.environ.get("GEMINI_API_KEY") or \
                     st.secrets.get("general", {}).get("gemini_key", "")
    except:
        pass
    
    if shared_key:
        st.success("✨ Global Suite Key Active")
        gemini_key = shared_key
        with st.expander("Key Settings"):
            override_key = st.text_input("Override Global Key", type="password", help="Leave blank to use the shared suite key.")
            if override_key:
                gemini_key = override_key
    else:
        st.warning("⚠️ No shared key found.")
        gemini_key = st.text_input("Enter Gemini API Key", type="password")
    
    st.markdown("---")
    language = st.selectbox("🌍 Analysis Language", ["English", "Hindi", "Spanish", "French", "German", "Chinese"])
    domain = st.selectbox("🏗️ Technology Domain", ["General", "Medical Devices", "IoT & Smart Systems", "AI & Software", "Electronics", "Biotechnology", "Mechanical"])
    jurisdiction = st.multiselect("⚖️ Target Jurisdictions", ["India", "USA", "PCT (International)", "European Union", "Japan"], default=["India", "USA"])
    
    st.info("Advanced Patent Suite v2.5")
    st.caption("Secure Professional Edition")

# --- TEXT REPORT GENERATOR ---
def create_txt_report(data, invention_name):
    report = f"==================================================\n"
    report += f"      ADVANCED PATENT ANALYSIS REPORT\n"
    report += f"==================================================\n\n"
    report += f"Invention: {invention_name}\n"
    report += f"Date: {os.popen('date /t').read().strip()}\n"
    report += f"-"*50 + "\n"
    report += f"Novelty Score: {data.get('novelty_score', 'N/A')}%\n"
    report += f"Risk Level: {data.get('risk_level', 'N/A')}\n"
    report += f"TRL Estimate: {data.get('trl_level', 'N/A')}\n"
    report += f"-"*50 + "\n\n"
    
    report += "SECTION 1: TECHNICAL ANALYSIS\n"
    report += data.get('analysis', 'N/A') + "\n\n"
    
    report += "SECTION 2: FILING & JURISDICTIONAL STRATEGY\n"
    report += data.get('filing_advice', 'N/A') + "\n\n"
    
    report += "SECTION 3: DRAFT CLAIMS (PRELIMINARY)\n"
    report += data.get('draft_claims', 'N/A') + "\n\n"
    
    report += "SECTION 4: PATENTABILITY IMPROVEMENTS\n"
    suggestions = data.get('suggestions', [])
    if isinstance(suggestions, list):
        for s in suggestions:
            report += f"[ ] {s}\n"
    else:
        report += str(suggestions) + "\n"
        
    report += "\nSECTION 5: PRIOR ART SEARCH RESULTS\n"
    for art in data.get('similar_art', []):
        report += f"- {art.get('title')} ({art.get('id')})\n  Link: {art.get('link')}\n\n"
        
    report += "\n" + "="*50 + "\n"
    report += "Generated by Advanced Patent Suite AI\n"
    return report

# --- PDF REPORT GENERATOR ---
def create_pdf_report(data, invention_name):
    from fpdf.enums import XPos, YPos
    
    class PDF(FPDF):
        def header(self):
            # Background Rect for header
            self.set_fill_color(30, 58, 138) # Dark Blue
            self.rect(0, 0, 210, 40, 'F')
            self.set_font('Helvetica', 'B', 16)
            self.set_text_color(255, 255, 255)
            self.set_y(15)
            self.set_x(20)
            self.cell(170, 10, 'ADVANCED PATENT SUITE - IP REPORT', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_x(20)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(170, 10, f'Page {self.page_no()} | Confidential | {invention_name}', align='C')

    # A4: 210 x 297 mm
    pdf = PDF()
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    
    font_main = "Helvetica"
    
    # Subject Line
    pdf.set_y(45)
    pdf.set_x(20)
    pdf.set_font(font_main, 'B', 14)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(170, 10, f"Subject: {invention_name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)

    # Metrics Grid (170mm total)
    pdf.set_fill_color(241, 245, 249)
    pdf.set_draw_color(203, 213, 225)
    
    pdf.set_x(20)
    pdf.set_font(font_main, 'B', 11)
    pdf.cell(55, 10, "Novelty Score", 1, 0, 'C', True)
    pdf.cell(55, 10, "Legal Risk", 1, 0, 'C', True)
    pdf.cell(60, 10, "TRL Level", 1, 1, 'C', True)
    
    pdf.set_x(20)
    pdf.set_font(font_main, '', 14)
    pdf.cell(55, 15, f"{data.get('novelty_score', 'N/A')}%", 1, 0, 'C')
    pdf.cell(55, 15, f"{data.get('risk_level', 'N/A')}", 1, 0, 'C')
    pdf.cell(60, 15, f"Level {data.get('trl_level', 'N/A')}", 1, 1, 'C')
    pdf.ln(10)

    def safe_text(text):
        if not text: return "N/A"
        text = str(text)
        mapping = {
            '\u2022': '-', '\u2013': '-', '\u2014': '-', 
            '\u201c': '"', '\u201d': '"', '\u2018': "'", '\u2019': "'",
            '\u2122': '(TM)', '\u00ae': '(R)', '\u00a9': '(C)',
            '\u00b0': ' deg'
        }
        for k, v in mapping.items():
            text = text.replace(k, v)
        return text.encode('latin-1', 'ignore').decode('latin-1')

    # Content Sections
    sections = [
        ("1. EXECUTIVE TECHNICAL ANALYSIS", data.get('analysis', 'N/A')),
        ("2. FILING & JURISDICTIONAL STRATEGY", data.get('filing_advice', 'N/A')),
        ("3. PRELIMINARY DRAFT CLAIMS", data.get('draft_claims', 'N/A'))
    ]

    for title, content in sections:
        pdf.set_x(20)
        pdf.set_font(font_main, 'B', 12)
        pdf.set_text_color(30, 58, 138)
        pdf.set_fill_color(226, 232, 240)
        pdf.cell(170, 10, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        pdf.ln(2)
        
        pdf.set_x(20)
        pdf.set_font(font_main, '', 10)
        pdf.set_text_color(30, 41, 59)
        pdf.multi_cell(170, 6, safe_text(content))
        pdf.ln(5)

    # Suggestions
    pdf.set_x(20)
    pdf.set_font(font_main, 'B', 12)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(170, 10, "4. PATENTABILITY ROADMAP", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.set_font(font_main, '', 10)
    pdf.set_text_color(30, 41, 59)
    suggestions = data.get('suggestions', [])
    if isinstance(suggestions, list):
        for s in suggestions:
            pdf.set_x(20)
            pdf.multi_cell(170, 6, f"- {safe_text(s)}")
    else:
        pdf.set_x(20)
        pdf.multi_cell(170, 6, safe_text(suggestions))
    pdf.ln(5)

    # Prior Art
    pdf.add_page()
    pdf.set_x(20)
    pdf.set_font(font_main, 'B', 12)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(170, 10, "5. PRIOR ART & CITATIONS", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    for art in data.get('similar_art', []):
        pdf.set_x(20)
        pdf.set_font(font_main, 'B', 10)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(170, 7, f"{safe_text(art.get('title'))} ({safe_text(art.get('id'))})", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        pdf.set_x(20)
        pdf.set_font(font_main, '', 9)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(170, 5, f"Source: {safe_text(art.get('link'))}")
        pdf.ln(3)

    return bytes(pdf.output())

# --- AI LOGIC ---
def perform_advanced_analysis(invention_desc, research_context, api_key, lang, dom, jurs):
    try:
        genai.configure(api_key=api_key)
        models = ['gemini-pro-latest', 'gemini-flash-lite-latest', 'gemini-2.0-flash-lite']
        
        jur_context = ", ".join(jurs) if jurs else "Global (Analyze and recommend most suitable jurisdictions)"
        
        for m_name in models:
            try:
                model = genai.GenerativeModel(m_name)
                prompt = f"""
                You are a Senior Patent Attorney and Technical Analyst specializing in {dom}.
                Analyze the following invention in {lang}.
                
                Invention: {invention_desc}
                Research Context: {research_context}
                Target Jurisdictions: {jur_context}
                
                Provide a comprehensive analysis including:
                1. Novelty Score (0-100)
                2. Risk Level (Low/Medium/High)
                3. TRL (Technology Readiness Level) Estimation (1-9)
                4. Analysis: Comparison with existing patents and research papers.
                5. Filing Advice: Specific recommendations for {jur_context}. If no specific jurisdictions were provided, suggest the top 3 countries/regions where this should be filed.
                6. Draft Claims: Generate 1 independent and 2 dependent claims.
                7. Suggestions: How to improve patentability.
                8. Similar Art: List of 3 relevant patents/papers with snippets and search links.
                
                Return ONLY a JSON response:
                {{
                  "novelty_score": int,
                  "risk_level": "string",
                  "trl_level": "string",
                  "analysis": "string",
                  "filing_advice": "string",
                  "draft_claims": "string",
                  "suggestions": ["string"],
                  "similar_art": [{{ "title": "string", "id": "string", "snippet": "string", "link": "string" }}]
                }}
                """
                response = model.generate_content(prompt)
                return json.loads(response.text.strip().replace('```json', '').replace('```', ''))
            except: continue
        return None
    except Exception as e:
        st.error(f"Error: {e}")
        return None

# --- UI ---
st.title("🔍 Advanced Patent Novelty & Filing Suite")
st.markdown("Global prior art search, TRL estimation, claim drafting, and filing roadmap.")

col_a, col_b = st.columns(2)
with col_a:
    inv_title = st.text_input("Invention Title", placeholder="e.g., IoT-based Smart Irrigation Valve")
    inv_desc = st.text_area("Detailed Technical Description", height=250, placeholder="Explain the mechanics, logic, and novelty...")

with col_b:
    res_context = st.text_area("Research Context / Paper References (Optional)", height=325, placeholder="Paste snippets from related research papers or your own draft paper for combined analysis.")

if st.button("🛡️ Execute Comprehensive Analysis"):
    if not gemini_key or not inv_desc:
        st.warning("Please provide API key and invention description.")
    else:
        with st.spinner("Processing Global Databases..."):
            result = perform_advanced_analysis(inv_desc, res_context, gemini_key, language, domain, jurisdiction)
            
            if result:
                tabs = st.tabs(["📊 Novelty & TRL", "⚖️ Filing & Claims", "🔎 Prior Art", "📄 Report"])
                
                with tabs[0]:
                    c1, c2, c3 = st.columns(3)
                    c1.metric("Novelty Score", f"{result['novelty_score']}%")
                    c2.metric("Risk Level", result['risk_level'])
                    c3.metric("TRL Level", result['trl_level'])
                    st.subheader("Technical Analysis")
                    st.write(result['analysis'])
                    
                with tabs[1]:
                    jur_display = ", ".join(jurisdiction) if jurisdiction else "Global Recommendations"
                    st.subheader(f"Jurisdiction Advice ({jur_display})")
                    st.write(result['filing_advice'])
                    st.subheader("Draft Claims")
                    st.code(result['draft_claims'], language='text')
                    st.subheader("Improvement Roadmap")
                    for s in result['suggestions']: st.write(f"✅ {s}")
                    
                with tabs[2]:
                    st.subheader("Identified Patents & Research Papers")
                    for art in result['similar_art']:
                        with st.container():
                            st.markdown(f"""<div class='patent-card'><strong>{art['title']}</strong> ({art['id']})<br/>{art['snippet']}<br/><a href='{art['link']}' target='_blank'>Source Link</a></div>""", unsafe_allow_html=True)
                            
                with tabs[3]:
                    st.subheader("Download Full Report")
                    
                    col1, col2 = st.columns(2)
                    with col1:
                        # PDF Option (Primary)
                        try:
                            # Sanitize filename
                            safe_title = "".join([c for c in (inv_title or "Unnamed") if c.isalnum() or c in (" ", "_", "-")]).strip()
                            pdf_data = create_pdf_report(result, inv_title or "Unnamed Invention")
                            st.download_button(label="📕 Download Technical Report (PDF)", data=pdf_data, file_name=f"Patent_Report_{safe_title}.pdf", mime="application/pdf")
                        except Exception as e:
                            st.error(f"PDF Error: {e}")
                            st.info("Please use the TXT version below.")
                    
                    with col2:
                        # Text Option (Fallback/Alternative)
                        txt_data = create_txt_report(result, inv_title or "Unnamed Invention")
                        st.download_button(label="📄 Download Technical Report (TXT)", data=txt_data, file_name=f"Patent_Report_{inv_title}.txt", mime="text/plain")
                    
                    st.info("PDF format is recommended for professional use. TXT is provided for maximum compatibility.")
            else:
                st.error("Analysis failed. Please try again.")
